name: Dependabot Auto Approve

on: 
  pull_request:
    branches:
      - master
  
jobs:
  actor_filter:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/bin/filter@3c0b4f0e63ea54ea5df2914b4fabf383368cd0da"
        with: 
          args: "actor dependabot-preview[bot] dependabot[bot]"
      
  auto_approve:
    runs-on: ubuntu-latest
    needs: actor_filter
    steps:
      - uses: "hmarr/auto-approve-action@v1.0.0"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
